language: ruby

install:
  - gem install mdl awesome_bot

script:
  - mdl README.md
  - awesome_bot README.md --allow-redirect

  # See if contributor was added
  - if git diff-tree --no-commit-id --name-only -r $(git rev-parse HEAD) | grep CONTRIBUTORS.md; then
      exit 0;
    else
      echo "⚠️ Contributor did not add themselve to the CONTRIBUTORS.md list";
      exit 1;
    fi
